version: '3'

services:
  traefik:
    image: traefik
    container_name: traekik
    command: --web --docker --docker.domain=pixhub.fr --logLevel=DEBUG
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - webgateway
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.pixhub.fr"

networks:
  webgateway:
    driver: bridge
