version: '3'

services:
  traefik:
    image: traefik
    container_name: traekik
    command: --web --docker --docker.domain=pixhub.fr --logLevel=DEBUG
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
    networks:
      - dmz
    labels:
      - "traefik.frontend.rule=Host:traefik.pixhub.fr"
      - "traefik.backend=traefik-dashboard"
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_dmz"

networks:
  webgateway:
    driver: bridge
